server:
  port: 8080

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false

logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud: DEBUG